In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df=pd.DataFrame({
    "size":[
        's','m','l','xl','xxl',
        'xxl','l','l','m','xxl'
    ]
})
df.head(6)

  size
0    s
1    m
2    l
3   xl
4  xxl
5  xxl

In [8]:
ord_data=[['s','m','l','xl','xxl']]

In [11]:
oe=OrdinalEncoder(categories=ord_data)
oe.fit(df[['size']])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl', 'xxl']])

In [20]:
df['en_size']=oe.transform(df[['size']])
df.head(6)

  size  en_map_size  en_size
0    s            0      0.0
1    m            1      1.0
2    l            2      2.0
3   xl            3      3.0
4  xxl            4      4.0
5  xxl            4      4.0

In [22]:
# Using map function
ord_data_map={'s':0,
             'm':1,
             'l':2,
             'xl':3,
             'xxl':4}

In [21]:
df['en_map_size']=df['size'].map(ord_data_map)
df.head(6)

  size  en_map_size  en_size
0    s            0      0.0
1    m            1      1.0
2    l            2      2.0
3   xl            3      3.0
4  xxl            4      4.0
5  xxl            4      4.0

In [35]:
# By using real data - sklearn
dataset=pd.read_csv("student_habits_performance.csv")
dataset.head(6)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,NaN,0.0,NaN,1.1,NaN,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,NaN,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,NaN,1,High School,Poor,1,NaN,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,NaN,Good,1,Yes,26.8
4,S1004,19,Female,5.0,NaN,0.5,NaN,90.9,4.9,NaN,3,Master,NaN,1,No,66.4
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,Fair,1,Master,Average,4,No,100.0

In [36]:
dataset['diet_quality'].unique()

array(['Fair', 'Good', nan, 'Poor'], dtype=object)

In [37]:
dataset['diet_quality'] = dataset['diet_quality'].fillna(dataset['diet_quality'].mode()[0])

In [38]:
dataset.head(6)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,NaN,0.0,NaN,1.1,NaN,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,NaN,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Fair,1,High School,Poor,1,NaN,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,NaN,Good,1,Yes,26.8
4,S1004,19,Female,5.0,NaN,0.5,NaN,90.9,4.9,Fair,3,Master,NaN,1,No,66.4
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,Fair,1,Master,Average,4,No,100.0

In [39]:
dataset['diet_quality'].unique()

array(['Fair', 'Good', 'Poor'], dtype=object)

In [41]:
ord_data2=[['Fair', 'Good', 'Poor']]

In [42]:
oe_realdata=OrdinalEncoder(categories=ord_data2)

In [45]:
dataset['diet_quality']= oe_realdata.fit_transform(dataset[['diet_quality']])

In [47]:
dataset['diet_quality'].unique()

array([0., 1., 2.])

In [46]:
dataset.head(6)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,en_diet_quality
0,S1000,23,NaN,0.0,NaN,1.1,NaN,85.0,8.0,0.0,6,Master,Average,8,Yes,56.2,0.0
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,1.0,6,High School,NaN,8,No,100.0,1.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,0.0,1,High School,Poor,1,NaN,34.3,0.0
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,2.0,4,NaN,Good,1,Yes,26.8,2.0
4,S1004,19,Female,5.0,NaN,0.5,NaN,90.9,4.9,0.0,3,Master,NaN,1,No,66.4,0.0
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,0.0,1,Master,Average,4,No,100.0,0.0